language: java
jdk: oraclejdk8
install: true

script:
  - ./mvnw test -q

deploy:
  provider: heroku
  api_key:
    secure: Rr+JwF/CQgL1ronDRdKNuyJG8r5MZVxFfNZ1YpW2bU38/avwnSmi7ouFzuVFc0Hu1fteIoylhAgI6rFYMC9C4jZiHQ8kcDEJwNRk9rjluFwxYmZpDCSSUSdhi0TPxY7GPvPJlYxSO6vcM9RAWRdXIOk5wJrgZlfP+bypmVLXItKjw+vttqSB2mBF5lRX7Vz+EjngQQ7Zt2aiCcCUTloXiEZAVJSA7dwxW5QqE4IGHNt3ZBJAM/3cBkgNSXzHFLKfkEQYdSSI+QCeOhTft1DYTP3zSCKCdB+eALNTVa8e+4XsKtzET50WQjk6XhvP16kw5hK72KR+TVXMWGKff1Y52uL39O+q7QrHyjp9FsoBXSyi06MXcwhtwH7/OH1claa7lDGcmiEyqvTxxH/LZjENrO9x/HSxhEqdRwOndrMwByIe0VTxf86A7+BJ6tEFd08sK8uwHqmApZ6XTdkGpomAEcBDdNGsAbFN9yfjhMCeGiF/F+UXgAo/AqjOK9SGBKPZGZPOIQ5u2VNrv9VXrd7RVvd8XiXB53+LWbKaW393g+oOTo7dJRP9vY1d9gSVg4N4RjzBMiorUvshZT2nctlfBcmHWg8YOXBJEGZXoLC2UFKQW+/0jhsR4CLR3xymKf0lmVx/8Oy3BrQcVjkRs1mOK3wfoPHL/lFFfFSXUBXhTOE=
  app: tacs-grupo1
  strategy: git
  on:
    all_branches: true
