language: java
jdk: oraclejdk8
install: true

script:
  - "./mvnw test -q"

deploy:
  provider: heroku
  api_key:
    secure: VsN7I4aCO/1OfI3Oz2s0QtbmZEJcv6uAdiKWgzcU8uHd9RazJCUyUEMRjFTdR9xUGo6kreHPLPnUQxvtv9yKqKbyN/TaehXLjI84+ycNayM8glZ3OEMafqQXuXFsQBFdEbCkRWhUubiAF6FDcUCT8erZlDP/XW9Guu+lF5/FXsKFQh57F3gHOTHm3l2ocDMHWbJjHOYY0SYLSIMQvXSaoJ5l5bGraBKgRCxi7oAmAtoagfJwOI5efmdq+Xm9FxQEdVfd9p9AT7PewLO7zqsBYd05Kf3UlXczExG6/5e6Ve0nTaIThuusr46Nge4f7kAiiTdsgnOkVKDhuQYKCoqROViInNzKfi9Nn3U+kWBvYvJG4jmn9EoND7PsoDurVQoLIfeo8DuFC1gnYQU4Xycz0V+p0EkGTv8UST/JnLJE9uJnsF09paYSXxJmlEOoFByRPwKRgtDh86oOFrEJJ4sYJWtp3eMfTSUEh+HbqQ1ezeVzy9k1M7WSwSW3Wk4rBhzy3K20RcliuAvkS/tcrl4p2l7eg4tAG6+r19NO+uNGWH0FmXBZl483LfMY4HFKpm5iVZbj6ISXTWs+SESF1zL11aUecqGMMMqWGQmjoeOqfKfNYYB+0FLc9MvgHCyS2alFv2eSRvfEtIk0lEZtlh7fKuxBl4kwNxy8psMLQ9tZgA0=
  app: tacs-grupo1
  on:
    all_branches: true
