language: generic

sudo: required

services:
  - docker

script:
  - travis_wait docker build -t jonigl/tacs-grupo1:1.0.0 .

deploy:
  provider: heroku
  api_key:
    secure: A4mbjVDgnWEPQL1UZ25+J5mPSOaGoZioikc7NAbeUGhAZHvh/xRyDkUsSVUCjYwdrw5juiVO1N+qMPXJGO3HC6vmUFNzp8pkzL3B2ES/J2FNdHZxSW8DuWw9PGO6rF/NEbB7Tkodjw+b6QGjoLAAH0KGAp8rMpgFNDTv+s1bkZwR5SWva2Ctprgj22sf6MLYBHDaYsiDJIPKQ7DVFkKo44+WEJ8/+rpb6xGo6L0frPoAtXKLK6j9u35kv1F7L7zMBiiK+S5xgAzKnL73z0y6s+zfEp3OW8Ye3JW7hzZO8pS6tQXU+H0SgLm/mALPEQ3OBblnb0jRHvb0LOSyT2Cevfa5ToSQADENTdB0y5O9G7PfqB3WzijkC4SokIlnIII27yVKvhjA4QC5ZryrnqvAH3T6AgafhjfvFAgUwu/KHahRkhOO6MXiNHk1T8LwOjK3lo3/b7rEQo/8VMwGmBXp8vbkm2QK49PlLFKFLNw2jC2tiFs8jYrEjjN8qdmwNsx1eHTMZdNSdpESoE6IO79jSsgj3HhWZL+1f4bxK68mVYRoV5Ec63NI/Zc71yHmNNDs3j0WoLUzKjREOTiQ0J9PSjkCbpZYYO0FnLDRdpg9ETqBtZHK+/8XSZ9tm9+cTLFRGQoybgOQ7HrejFbiB0MCZS6AQfuuSa/uvRaK/NiLofc=
  app: tacs-grupo1-travis-ci
  strategy: git

