language: java
jdk: oraclejdk8
install: true

script:
  - "./mvnw test -q"

deploy:
  provider: heroku
  api_key:
    secure: a4sIqWrLhv9rc9w3ndbFbHhRXtm5IQpBY0z822TkVM1lCWDAAxOWmfm0J3lRRl3iN1IxMLYURT70Pyz8AlpfL4Jo9VhXIVVxIAbA1wnu52ygytTezddpR38oh8tdn82Ry6buHnT6PG9HEPYi15tpD4Z+vxKGc4hYsiUe4utSOig8uXEyhu0vm/zkGzGMOxf0xeJXj311/X9n/q/d+xW35JzD13wS/V981nrndBBnAeZak1ifJzdVzU9vBlBLDsGb+aBcBndoQJveEINWHRAvpqfT1gzJNyaPQaDWbi59q//ALFce1NRxofBhagQt13ckGDC+eYXnwrtMPOObzQkwOJhUfMAtJqAbhLHtIbQOQwqpAFg6aWW3Hxj1t4Ru6gKBFfiKZ9NhkaQgGqp1pl4zb9pcj67qcb4Qf7YypuJ3P8BtBM8qQwVzXyB/BlWtEMeXRWy7F5zC3w/HATJoTX50Y6uqQ+JKk3sKSD8CJ4VtN7I+U7kZYDn7Hiagp4NMQ6A54IwCrHkp1PIWa9L7MqoaS5pUlORJgBjYsbL+YOehOwx8TGWU9DIdjjyiXA6uAhPshiz5PJwqfH9ZflNNX2645C3ueDyxYTV5/zpQajn4OYqMYosChr+vVr8b7m3cvI7RjNbkHH2WoXAOWGYYiLHTqDv2VauY/VNnx5juCVyrNnE=
  app: tacs-grupo1
  strategy: git
  on:
    all_branches: true
