language: java
jdk: oraclejdk8
install: true

script:
  - "./mvnw install -q -Dmaven.test.skip=true"

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: tacs-grupo1
  on:
    all_branches: true
