version: '3'
services:
  api:
    restart: always
    image: jonigl/tacs-grupo1:1.0.0
    container_name: "api"
    ports:
    - 8080:8080
    links:
    - mongodb
    depends_on:
    - "mongodb"
    environment:
      - MONGO_URI=mongodb://mongodb/eventapp
  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
